### ISSUE TITLE
Add inheritance utilities

### ISSUE THREAD

**Issue by necolas** [suitcss/utils-text#5]
``` css
/**
 * Inherit the ancestor's text color. Useful for links that need to look like
 * text until interacted with (e.g., user's full name).
 */

.u-textInheritColor {
  color: inherit;
}

/**
 * Inherit the ancestor's text color for all states. Useful for links that need
 * to look as if they aren't links (e.g., a card's description).
 */

.u-textInheritAllColor,
.u-textInheritAllColor:hover,
.u-textInheritAllColor:focus,
.u-textInheritAllColor:active {
  color: inherit;
}
```
